Update auto-fork.yml

diff --git a/.github/workflows/auto-fork.yml b/.github/workflows/auto-fork.yml
--- a/.github/workflows/auto-fork.yml
+++ b/.github/workflows/auto-fork.yml
@@ -1,27 +1,34 @@
-name: Auto Fork Repository
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    # 每 2 天执行一次，这里使用 cron 表达式，在每天的 0 点 0 分检查，由于我们设置了每 2 天执行，所以实际每 2 天执行一次
-    - cron: '0 0 */2 * *'
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  fork-repo:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fork Repository
-        env:
-          # 将之前获取的个人访问令牌添加到仓库的 Secrets 中，命名为 ACCESS_TOKEN
-          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-          # 替换为你要 Fork 的源仓库的拥有者
-          SOURCE_OWNER: "Hiram-Wong"
-          # 替换为你要 Fork 的源仓库的名称
-          SOURCE_REPO: "ZyPlayer"
-        run: |
-          curl -X POST \
-            -H "Authorization: token $GITHUB_TOKEN" \
-            -H "Accept: application/vnd.github.v3+json" \
-            "https://api.github.com/repos/$SOURCE_OWNER/$SOURCE_REPO/forks"
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.ACCESS_TOKEN }}
+                  upstream_sync_repo: Hiram-Wong/ZyPlayer
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
 
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
